dataset:
  root: /home/li325/qing_workspace/dataset/UMD/part-affordance-dataset
  patch_size: 14
  pad_to_patch_multiple: true

model:
  target: dinov2
  config_path: configs/models/dinov2.yaml
  overrides: {}

training:
  num_workers: 0
