model_dir: ../../../model_for_test/FLUX.1-dev
flow_checkpoint: flux1-dev.safetensors
ae_checkpoint: ae.safetensors
layers_to_hook: ["single_9", "single_19", "single_29", "single_37"]
primary_layer: single_9
output_dir_name: flux_new_multi_single
head:
  type: multi_layer_linear
  feature_keys: ["single_9", "single_19", "single_29", "single_37"]
  primary_key: single_9
  fuse_mode: concat
  use_batchnorm: true
  dropout: 0.0
time_step: 1
guidance_strength: 1.0
disable_guidance: false