model_dir: ../../../model_for_test/FLUX.1-dev
flow_checkpoint: flux1-dev.safetensors
ae_checkpoint: ae.safetensors
layers_to_hook: ["double_3", "double_8", "double_13", "double_18"]
primary_layer: double_3
output_dir_name: flux_new_multi_double
head:
  type: multi_layer_linear
  feature_keys: ["double_3", "double_8", "double_13", "double_18"]
  primary_key: double_3
  fuse_mode: concat
  use_batchnorm: true
  dropout: 0.0
time_step: 1
guidance_strength: 1.0
disable_guidance: false