model_id: hf-hub:laion/CLIP-ViT-B-16-laion2B-s34B-b88K
patch_size: 16
precision: fp32
repo_path: /home/li325/qing_workspace/export/open_clip/src
layers_to_hook: [11]
# [2, 5, 8, 11]
primary_layer: 11
output_dir_name: openclip_depth_lay11
head:
  type: multi_layer_linear
  feature_keys: [11]
  primary_key: 11
  fuse_mode: concat
  use_batchnorm: true
  dropout: 0.0
