model_id: google/siglip2-giant-opt-patch16-384
precision: bf16
patch_size: 16
layers_to_hook: [9, 19, 29, 39]
output_dir_name: siglip2_lay9
head:
  type: multi_layer_linear
  feature_keys: [9, 19, 29, 39]
  primary_key: 9
  fuse_mode: concat
  use_batchnorm: true
  dropout: 0.0
