model_id: google/siglip-large-patch16-384
precision: bf16
patch_size: 16
layers_to_hook: [ 23]
output_dir_name: siglip_single23
head:
  type: multi_layer_linear
  feature_keys: [ 23]
  primary_key: 23
  fuse_mode: concat
  use_batchnorm: true
  dropout: 0.0
