dataset:
  geometry:
    use_depth: false
    use_normal: true

model:
  params:
    layers_to_hook: [up_0]
    primary_layer: up_0
    head:
      feature_keys: [up_0]
      primary_key: up_0
    output_dir_name: sd/up0_normal

