dataset:
  geometry:
    use_depth: false
    use_normal: true

model:
  params:
    layers_to_hook: [up_1]
    primary_layer: up_1
    head:
      feature_keys: [up_1]
      primary_key: up_1
    output_dir_name: sd/up1_normal

