dataset:
  geometry:
    use_depth: false
    use_normal: true

model:
  params:
    layers_to_hook: [up_3]
    primary_layer: up_3
    head:
      feature_keys: [up_3]
      primary_key: up_3
    output_dir_name: sd/up3_normal

