dataset:
  geometry:
    use_depth: false
    use_normal: true

model:
  params:
    layers_to_hook: [2]
    primary_layer: 2
    head:
      feature_keys: [2]
      primary_key: 2
    output_dir_name: dinov2/2_normal

